ALTER DATABASE db1 set CHANGE_TRACKING = ON (CHANGE_RETENTION = 2 DAYS, AUTO_CLEANUP = ON);

GO
USE db1;
GO
ALTER TABLE SalesLT.SalesOrderDetail
ENABLE CHANGE_TRACKING
WITH (TRACK_COLUMNS_UPDATED = ON);   -- optional but helpful
GO
